### ISSUE TITLE
[suggestion] fishforfirst

### ISSUE THREAD

**Issue by Zursai** [Slackaduts/Deimos-Wizard101#26]
Add a 'fishforfirst' command to scripting.
example:
p1 fishforfirst
would teleport p1 into the battle, and then relog and friendtp to another player in the dungeon until the wizards are first in the battle, at which point the script would continue.

**Comment by Slackaduts** [comment]
Will not implement this (adventure parties have a feature for forcing this I believe), as I personally dislike friend TP. Feel free to impl yourself though and I'd be happy to add it.
