### ISSUE TITLE
[suggestion] client_to_buff option

### ISSUE THREAD

**Issue by Zursai** [Slackaduts/Deimos-Wizard101#27]
Just been trying to set up a bot for a boss.
Auto combat seems to want to put elemental and balance blades on an account that doesn't have any hits in deck.
Could another setting, client_to_buff, be added to the config, so that the user can specify exactly which account is hitting.
This would make the bot much more efficient, and give it a higher success rate.

Just a thought, but would be extremely useful if this could be added.

**Comment by Slackaduts** [comment]
Combat is currently frozen features-wise, as none of us know 100% of what it does anymore, and it has some fundamental stability issues, and is also blind to conditionals.

I'll consider adding this if we ever do another incarnation of auto combat, but it's just not practical to spend more time on old combat.
