### ISSUE TITLE
Deimos loads then closes after quickly downloading

### ISSUE THREAD

**Issue by ZaeThePrince** [Slackaduts/Deimos-Wizard101#69]
Trying to figure out why deimos opens then closes. Tried deleting then reinstalling doesn't work. Closed w101 Which auto-closed CMD :[ Please help

**Comment by chantellU** [comment]
oyu ratted

**Comment by Slackaduts** [comment]
We do not do support in issues.

Please head to the discord server's support channel if you need support.

**Comment by chantellU** [comment]
lol trying to hide what you sid with ur compiled pre built shid
