### ISSUE TITLE
Deimos not opening windows 11

### ISSUE THREAD

**Issue by IVIiizchief** [Slackaduts/Deimos-Wizard101#76]
Deimos worked fine for me before but now it wont open, every time I try to open it I get "Operation did not complete successfully because the file contains a virus or potentially unwanted software" I've tried asking my friends that have been using it for a long time but they do not know. Is there any way I can fix it?

**Comment by Slackaduts** [comment]
Disable your antivirus software.

**Comment by Slackaduts** [comment]
Additionally, ensure you've downloaded it from the GitHub, or  the posted link in the official discord server. Good day.
